implement api /bdimage/cover-thread add cover image to thread
xfrocks/bdImage pull request #13
Opened 2020-06-10 04:34 UTC by thanhtan1105

Dear a @daohoangson 

Em gửi Pull request cho api /bdimage/cover-thread

2020-06-10 23:40 UTC, luutruong commented
Ủa cái này xài hẳn route mới luôn à @thanhtan1105 . Sao ko xài cái có sẵn là `/threads/:threadId/cover` ?

2020-06-11 01:05 UTC, daohoangson requested changes

2020-06-11 01:05 UTC, daohoangson commented on library/bdImage/ControllerApi/Thread.php
> +    public function actionPostCoverThread()
Xài POST `/threads/:id/image` luôn nha.

2020-06-11 01:05 UTC, daohoangson commented on library/bdImage/ControllerApi/Thread.php
> +        if (empty($thread)) {
Phải check quyền nữa nha.

2020-06-11 01:05 UTC, daohoangson commented on library/bdImage/ControllerApi/Thread.php
> +        $pickedImage = $picker->getPickedData();
Điều chỉnh `getPickedData` để nếu submit bằng api thì không cần gửi lên `is_cover_included=1` hén.

2020-06-11 01:05 UTC, daohoangson commented on library/bdImage/ControllerApi/Thread.php
> +        $pickedImage = $picker->getPickedData();
Cũng không cần `bdimage_included=1` luôn. Các param thì cũng bỏ prefix `bdimage_` luôn nè.

2020-06-15 06:16 UTC, thanhtan1105 commented on library/bdImage/ControllerApi/Thread.php
> +        if (empty($thread)) {
e thấy bên trong có check permission là 
"$visitor->hasPermission('general', 'bdImage_setCover')". 

Chỗ thread này mình thêm quyền ? ['general', 'bdImage_setCover'] đc không anh ?

2020-06-15 06:23 UTC, daohoangson commented on library/bdImage/ControllerApi/Thread.php
> +        if (empty($thread)) {
Đó là quyền set cover. Còn quyền set image nó ăn theo quyền edit thread thì phải. Check public controller á.

2020-06-15 06:53 UTC, thanhtan1105 commented on library/bdImage/ControllerApi/Thread.php
> +        if (empty($thread)) {
<img width="928" alt="Screen Shot 2020-06-15 at 13 40 01" src="https://user-images.githubusercontent.com/12711672/84625575-b8e9ff00-af0d-11ea-9a4e-f4262c488e05.png">

Em check thì nó chỉ cần permission `canViewPost`

2020-06-15 07:16 UTC, daohoangson commented on library/bdImage/ControllerApi/Thread.php
> +        if (empty($thread)) {
Oh, cái này nó check thiếu á. Trong API check thêm permission này nha:

```php
        $visitor = XenForo_Visitor::getInstance();
        if (!$visitor->hasPermission('general', 'bdImage_usePicker')) {
            xxx();
        }
```

2020-06-15 17:05 UTC, thanhtan1105 commented on library/bdImage/ControllerApi/Thread.php
> +        if (empty($thread)) {
tks anh Sơn nhiều ạ :D

2020-06-15 17:16 UTC, thanhtan1105 commented on library/bdImage/ControllerApi/Thread.php
> +        $pickedImage = $picker->getPickedData();
em đã fix rồi nah a ơi

2020-06-15 17:16 UTC, thanhtan1105 commented on library/bdImage/ControllerApi/Thread.php
> +        if (empty($thread)) {
done rồi ạ

2020-06-15 17:16 UTC, thanhtan1105 commented on library/bdImage/ControllerApi/Thread.php
> +    public function actionPostCoverThread()
done :D

2020-06-15 17:17 UTC, thanhtan1105 commented
> Ủa cái này xài hẳn route mới luôn à @thanhtan1105 . Sao ko xài cái có sẵn là `/threads/:threadId/cover` ?

a update lại link rồi nhen

2020-06-16 08:08 UTC, daohoangson requested changes

2020-06-16 08:08 UTC, daohoangson commented on README.md
> +6. Also create Data Writer and Model for your project
4 -> 6 luôn à 🤣

2020-06-16 08:08 UTC, daohoangson commented on README.md
> +## To start developing APIs
Đoạn này không có ý nghĩa lắm. Chắc bỏ?

2020-06-16 08:08 UTC, daohoangson commented on README.md
> +All APIs of Rating follows the structure of bdApi (https://github.com/xfrocks/bdApi/blob/master/docs/api.markdown).
APIs of Rating?

2020-06-16 08:08 UTC, daohoangson commented on README.md
> +### POST `/threads/:thread_id/image`
Xài `:threadId` nhé

2020-06-16 08:08 UTC, daohoangson commented on README.md
> +Add cover to thread
`Set thread image` có vẻ đúng hơn?

2020-06-16 08:08 UTC, daohoangson commented on README.md
> +- `image`: json data, image data
Bắt user tự soạn json không hợp lý vì user không biết đường nào mà chuẩn bị cả (có nhiều key `url`, `type`, etc.). Chắc phải trả về danh sách các images để user chọn và submit ngược lại. 

Data trả về chèn vô ngay cái GET `/post/:postId/editor-config` cũng hay?

2020-06-16 08:08 UTC, daohoangson commented on README.md
> +- `extra_data[is_cover]`: render as thread top cover image, default value: `false`
Để `is_cover` thôi, dẹp luôn `extra_data` nhé.

2020-06-16 08:08 UTC, daohoangson commented on README.md
> +--form 'other=' \
`other` là cái gì?

2020-06-16 08:08 UTC, daohoangson commented on README.md
> +User want to update cover to thread must have `bdImage_setCover`, `bdImage_usePicker` permission.
Trả về thêm key `permissions.edit_image` (tương tự `edit_title`) trong thread data nhé.

2020-06-16 08:08 UTC, daohoangson commented on library/bdImage/ControllerHelper/Picker.php
> +            XenForo_Helper_File::log('log', __LINE__);
Không commit debug các loại lên repo nhé.

2020-06-16 08:08 UTC, daohoangson commented on library/bdImage/ControllerHelper/Picker.php
> +            $prefix.'image' => XenForo_Input::STRING,
Sai coding convention

2020-06-16 08:08 UTC, daohoangson commented on library/bdImage/Listener.php
> +    public static function api_setup_routes(array &$routes)
Đoạn này hình như dư.

2020-06-16 08:08 UTC, daohoangson commented on library/bdImage/ControllerHelper/Picker.php
> +    public static $emptyPrefix = '';
Empty string cho vô variable làm gì hén?

2020-06-16 08:08 UTC, daohoangson commented on library/bdImage/ControllerHelper/Picker.php
> +    public static $emptyPrefix = '';
Mà lại để public, tức là ở ngoài sửa vô được? Tại sao?

2020-06-16 08:08 UTC, daohoangson commented on library/bdImage/bdApi/ControllerApi/Thread.php
> +        return $this->responseError(new Xenforo_Phrase('bdimage_image_not_found'), 400);
Flow error thì đưa lên trên để return sớm luôn.

```php
if (!is_string($pickedImage)) {
    return $this->responseError(new Xenforo_Phrase('bdimage_image_not_found'), 400);
}
```

2020-06-22 13:47 UTC, thanhtan1105 commented on README.md
> +- `image`: json data, image data
vậy em làm thêm cái api Get nhen

2020-06-22 13:48 UTC, thanhtan1105 commented on README.md
> +--form 'other=' \
trên gieo diện nó có option other anh dùng để chèn 1 tấm hình mà không có trong first post

2020-06-24 14:01 UTC, luutruong commented on library/bdImage/bdApi/ControllerApi/Thread.php
> +        $pickedImageUnpacked = bdImage_Helper_Data::unpack($pickedImage);
Đoạn này lấy từ $dw ra cho chắc nha anh. Vì khi set vô thì có xử lý riêng nữa. `$threadDw->bdImage_getThreadImage()`

2020-06-26 06:59 UTC, thanhtan1105 commented on README.md
> +- `extra_data[is_cover]`: render as thread top cover image, default value: `false`
bên trong em đang lấy data theo logic là 

$extraDataInput = new XenForo_Input($this->_controller->getInput()->filterSingle(
            $prefix . 'extra_data',
            XenForo_Input::ARRAY_SIMPLE
        ));

Nên chắc keep extra_data a ơi

2020-06-26 06:59 UTC, thanhtan1105 commented on README.md
> +User want to update cover to thread must have `bdImage_setCover`, `bdImage_usePicker` permission.
trả về thêm key lúc get first post hở a ?

2020-06-26 06:59 UTC, thanhtan1105 commented on library/bdImage/bdApi/ControllerApi/Thread.php
> +        $pickedImageUnpacked = bdImage_Helper_Data::unpack($pickedImage);
okie a xử rồi nah :D

2020-06-26 15:06 UTC, daohoangson commented on README.md
> +- `extra_data[is_cover]`: render as thread top cover image, default value: `false`
Vậy sửa ở trong hoặc truyền từ ngoài vào sao đó nha. API param để extra nó kì kì.

2020-06-26 15:08 UTC, daohoangson commented on README.md
> +User want to update cover to thread must have `bdImage_setCover`, `bdImage_usePicker` permission.
Cái này lúc comment ý là lúc get thread á.

2020-06-26 22:52 UTC, luutruong commented on library/bdImage/bdApi/ControllerApi/Thread.php
> +            $logParams = bdImage_Helper_Data::unpack($pickedImage);
`$threadDw->bdImage_getThreadImage()` nó đã unpack sẵn rồi anh. Ko cần đoạn này nha.

2020-06-27 23:54 UTC, luutruong commented on library/bdImage/bdApi/ControllerApi/Thread.php
> +        if (empty($thread)) {
Ở cái hàm `assertThreadValidAndViewable` lúc nào nó cũng trả về `$thread` á. Nên đoạn dưới check thừa nha a.

2020-06-27 23:55 UTC, luutruong commented on library/bdImage/Listener.php
> +            $extend[] = 'bdImage_bdApi_ControllerApi_Post';
Ủa sao e ko thấy file ControllerApi/Post.php đâu a nhỉ?

2020-06-28 03:17 UTC, luutruong commented on library/bdImage/bdApi/ControllerApi/Post.php
> +            $input = $this->_input->filter(array('post_id' => XenForo_Input::UINT));
Cái này check nếu `$response instanceof ... ` trước nha a chỉ chạy vô logic ở dưới khi cần thôi a.

2020-06-28 03:22 UTC, luutruong commented on library/bdImage/bdApi/ControllerApi/Post.php
> +            if ($response instanceof XenForo_ControllerResponse_View) {
Do ở trên check rồi thì đoạn này ko cần check lại nữa nha a.

2020-06-29 02:31 UTC, daohoangson requested changes

2020-06-29 02:31 UTC, daohoangson commented on README.md
> +User want to update cover to thread must have `bdImage_setCover`, `bdImage_usePicker` permission.
Cái permission`bdImage_usePicker` không tồn tại, hôm trước anh nói lộn á. Xoá đi nha.

2020-06-29 02:31 UTC, daohoangson commented on library/bdImage/ControllerHelper/Picker.php
> +     * @param null $data
Không có param `$data` sao lại có phpdoc nhỉ?

2020-06-29 02:31 UTC, daohoangson commented on library/bdImage/ControllerHelper/Picker.php
> +    public function getPickedImage($prefix)
Param `$prefix` là bắt buộc à?

2020-06-29 02:31 UTC, daohoangson commented on library/bdImage/addon-bdImage.xml
> -		max-height: initial;
File xml bị sửa mấy cái không liên quan rồi. Fix lại bằng cách:

1. Pull latest từ `master`
1. Import vô từ AdminCP (nhớ kiểm tra xem `xenforo1` và `DevHelper` đã latest chưa)
1. Tạo lại code event listener

2020-06-29 02:31 UTC, daohoangson commented on library/bdImage/bdApi/ControllerApi/Post.php
> +        if ($this->_isFieldIncluded('post_body_image') && ($response instanceof XenForo_ControllerResponse_View)) {
Để response key là `post_images` nha.

2020-06-29 02:31 UTC, daohoangson commented on library/bdImage/bdApi/ControllerApi/Post.php
> +            list($post, $thread, $forum) = $this->_getForumThreadPostHelper()->assertPostValidAndViewable($input['post_id']);
`$thread` với `$forum` không xài thì để trống nha.

```suggestion
            list($post,,) = $this->_getForumThreadPostHelper()->assertPostValidAndViewable($input['post_id']);
```

2020-06-29 02:31 UTC, daohoangson commented on library/bdImage/bdApi/Extend/Model/Thread.php
> +        $data['permissions']['edit_image'] = XenForo_Visitor::getInstance()->hasPermission('general',
Nếu check permission `bdImage_setCover` thì trả về vô `permissions.set_image_cover` nha. Còn `edit_image` thì check `canEditPost` là được rồi.

Với cả trả về thêm `links.edit_image` là `threads/:id/image` luôn nhé.

2020-06-29 02:31 UTC, daohoangson commented on library/bdImage/bdApi/Extend/Model/Thread.php
> +        $data['permissions']['edit_image'] = XenForo_Visitor::getInstance()->hasPermission('general',
Để response nó nhẹ hơn tí, check nếu có `permissions.edit_image` thì mới check tiếp và trả về `permissions.set_image_cover` và `links.edit_image` nha.

2020-06-29 02:31 UTC, daohoangson commented on README.md
> +5. Also create Data Writer and Model for your project
Cái bước này có vẻ không liên quan. Có khi là bỏ luôn cái đoạn "Getting started" vì dev vô đây là tự biết cái đó rồi.

2020-06-29 02:31 UTC, daohoangson commented on README.md
> +API prefix: `/bdimage`
Prefix này không đúng, mình tích hợp vô route `/threads` mà.

2020-06-29 02:31 UTC, daohoangson commented on README.md
> +- `other`: json data, image data
`other` này hình như là URL mà?

2020-06-29 02:31 UTC, daohoangson commented on README.md
> +- Request cover image other
Ví dụ này chưa thấy xài `other`?

2020-06-29 02:31 UTC, daohoangson commented on library/bdImage/ControllerHelper/Picker.php
> +        if ($prefix == bdImage_ControllerHelper_Picker::EMPTY_PREFIX) {
Xài `===`

2020-06-29 02:31 UTC, daohoangson commented on library/bdImage/bdApi/ControllerApi/Post.php
> +                array_push($postBodyImage, array('image_url' => $data['url'], 'data' => $imageData));
Xài `$postBodyImage[]` tiện hơn `array_push` hén?

2020-06-29 02:31 UTC, daohoangson commented on library/bdImage/bdApi/ControllerApi/Post.php
> +                array_push($postBodyImage, array('image_url' => $data['url'], 'data' => $imageData));
Cái key `'url'` không xài string mà xài constant `bdImage_Helper_Data::IMAGE_URL` nhé.

2020-07-01 02:46 UTC, daohoangson requested changes

2020-07-01 02:46 UTC, daohoangson commented on library/bdImage/bdApi/Extend/Model/Thread.php
> +
```suggestion
        $data['permissions']['edit_image'] = $this->_getPostModel()->canEditPost($firstPost, $thread, $forum);
        if ($data['permissions']['edit_image']) {
            $data['permissions']['set_image_cover'] = XenForo_Visitor::getInstance()->hasPermission('general', 'bdImage_setCover');
            $data['links']['edit_image'] = bdApi_Data_Helper_Core::safeBuildApiLink('threads/image', $thread);
        }

```

2020-07-01 02:46 UTC, daohoangson commented on library/bdImage/bdApi/ControllerApi/Thread.php
> +                // new XenForo_Phrase('moderator_log_thread_bdImage_setCover')
Cái dòng comment này không cần, xoá nha.

2020-07-01 02:46 UTC, daohoangson commented on library/bdImage/bdApi/ControllerApi/Thread.php
> +            // new XenForo_Phrase('moderator_log_thread_bdImage_remove')
Dòng này cũng không cần, bye luôn.

2020-07-01 02:46 UTC, daohoangson commented on library/bdImage/bdApi/ControllerApi/Post.php
> +                $data = json_decode($imageData, true);
Không xài json_decode nha.


```suggestion
                $data = bdImage_Helper_Data::unpack($imageData);
```

2020-07-01 02:46 UTC, daohoangson commented on library/bdImage/ControllerHelper/Picker.php
> +            array_push($extraData, ['is_cover' => $extraDataInput['is_cover']]);
Chưa được xài short array syntax nha.

2020-07-01 02:46 UTC, daohoangson commented on library/bdImage/ControllerHelper/Picker.php
> -            && $extraDataInput->filterSingle('is_cover_included', XenForo_Input::BOOLEAN)) {
Mất logic `is_cover_included` đâu rồi?!

2020-07-01 02:46 UTC, daohoangson commented on library/bdImage/ControllerHelper/Picker.php
> +        }
Rút gọn lại nha chế.

```suggestion
        $input = $this->_controller->getInput();
        if ($prefix !== bdImage_ControllerHelper_Picker::EMPTY_PREFIX) {
            $input = new XenForo_Input($input->filterSingle(
                $prefix . 'extra_data',
                XenForo_Input::ARRAY_SIMPLE
            ));
        }
        $extraDataInput = $input->filter(array(
            'is_cover' => XenForo_Input::BOOLEAN,
            'cover_color' => XenForo_Input::STRING
        ));
```

2020-07-03 01:30 UTC, daohoangson requested changes

2020-07-03 01:30 UTC, daohoangson commented on library/bdImage/ControllerHelper/Picker.php
> +            $extraData[] = array('is_cover' => $extraDataInput['is_cover']);
Chèn vô extra data kiểu này đâu có đúng? Sửa code mà chưa test lại hả chế?

2020-07-03 01:46 UTC, thanhtan1105 commented
![Screenshot 2020-07-03 08 46 06](https://user-images.githubusercontent.com/12711672/86423296-b9560880-bd09-11ea-9c80-068524108cdb.png)

Em đã xử lý nha a ơi :D

2020-07-03 01:53 UTC, daohoangson requested changes

2020-07-03 01:53 UTC, daohoangson commented on library/bdImage/bdApi/ControllerApi/Thread.php
> +        XenForo_Model_Log::logModeratorAction('thread', $thread, $logAction);
Refactor đoạn này đưa vô dw để tránh duplicate ở đây với controller public ha.

2020-07-03 01:53 UTC, daohoangson commented on library/bdImage/bdApi/ControllerApi/Post.php
> +            $postBodyImage = array();
Đổi tên `$postBodyImages` hoặc `$postImages` đi ha?

2020-07-05 15:22 UTC, daohoangson requested changes
Cái hàm `bdImage_saveThreadImage` không ý nghĩa lắm.

1. Nếu làm riêng một hàm trong đó lại set existing rồi set image thì làm một cái static rồi trong hàm đó create dw luôn thì hơn.
2. Còn không thì đưa đoạn log mod action vô post save của dw thì có được không?

Nếu theo phương án 2 thì bất cứ chỗ nào sửa image thì đều được log.

2020-07-07 05:31 UTC, merged